services:
  fastapi_madr_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  fastapi_madr_img:
    image: fastapi_madr_img
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - fastapi_madr_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fastapi_madr_database:5432/app_db

volumes:
  pgdata: